### ISSUE TITLE
`module not found` when installing `editable` in Tox 4.0

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/jwst#7388] opened 2022-12-09 16:10 UTC
when using `package = editable` to fix https://github.com/spacetelescope/jwst/issues/7386, the following error occurs for the `oldestdeps` run when running the `minimum_deps` script in `commands_pre`:
https://github.com/spacetelescope/jwst/actions/runs/3658899060/jobs/6184258846
```
pkg_resources.DistributionNotFound: The 'jwst' distribution was not found and is required by the application
```

**Comment by zacharyburnett** [comment] 2022-12-09 16:55
using `importlib.metadata` and `import jwst` have similar errors:
```
importlib.metadata.PackageNotFoundError: jwst
```
https://github.com/spacetelescope/jwst/actions/runs/3659224950/jobs/6184983651

**Comment by jdavies-st** [comment] 2022-12-19 12:49
I believe the issue is that the PEP 660 compliant behavior of the latest setuptools and pip break editable installs.

We could switch to pyargs for all unit tests in CI, but the problem would still remain for developers on their laptops wanting to do editable installs and quickly iterate with a few tests with pytest directly.  How does astropy resolve this?

2 legacy issues in this package that make resolving tricky:

- we don't use a src-layout for the code, and we package tests inside the runtime code, against the recommendations of best-practices for new python projects.  astropy has a similar issue, and seems to have resolved it, though they jump through lots of hoops to do so, and they do all their CI testing with pyargs.
- We don't package our scripts properly, i.e. via entry points and `console.scripts`.  That said, switching to the correct way for the failing script above actually makes it fail across the board on editable installs, suggesting that editable installs really are broken in the latest setuptools.  We could pin setuptools?  But this is independent of tox 4.

Theoretically we should be able to resolve as astropy has.  Thoughts?

**Comment by zacharyburnett** [comment] 2022-12-20 14:55
It might be better, in the long run, to package tests above the package directory, and also add the entry point scripts to `console.scripts` as modules instead of the legacy standalone scripts with `setup(scripts=[])`

**Closed** 2022-12-27 15:00 UTC
Labels: bug
