### ISSUE TITLE
datamodels warning Error validating header for HDU #0

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5995] opened 2021-04-28 19:05 UTC
_Issue [JP-2062](https://jira.stsci.edu/browse/JP-2062) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

With astropy 4.2.1, we are seeing a bunch of the following warnings in our unit tests:

```
/Users/jdavies/miniconda3/envs/test/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py:1187: VerifyWarning: Error validating header for HDU #0 (note: Astropy uses zero-based indexing).
      Header size is not multiple of 2880: 188
  There may be extra bytes after the last HDU or the file is corrupted.
```

To reproduce with a single unit test (there are dozens of others):

```
$ pytest jwst/stpipe/tests/test_step.py::test_hook_with_return
============================= test session starts =============================
platform darwin -- Python 3.9.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
crds_context: jwst_0717.pmap
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.3, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                              

jwst/stpipe/tests/test_step.py .                                        [100%]

============================== warnings summary ===============================
jwst/stpipe/tests/test_step.py::test_hook_with_return
  /Users/jdavies/miniconda3/envs/test/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py:1187: VerifyWarning: Error validating header for HDU #0 (note: Astropy uses zero-based indexing).
      Header size is not multiple of 2880: 188
  There may be extra bytes after the last HDU or the file is corrupted.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 1 passed, 1 warning in 1.53s =========================
```

**Comment by jdavies-st** [comment] 2021-04-28 19:06
More details on this here

https://github.com/asdf-format/asdf/pull/977

**Comment by nden** [comment] 2021-06-22 17:35
Most likely we need to regenerate the test file.

**Comment by hbushouse** [comment] 2022-03-25 13:11
Can't reproduce the problem using the latest astropy and asdf, so I'm closing.

**Closed by hbushouse** 2022-03-25 13:11 UTC
Labels: datamodels, Software Affected: datamodels

**Comment by stscijgbot-jp** [comment] 2022-10-14 19:51
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2062?focusedCommentId=578137#comment-578137):_

Just ran these tests (and many more) using asdf=2.9.2 and astropy=5.0 and did not get any of these warnings. So either the test files have already been updated or it's no longer an issue with these later versions of the dependencies. So I'm closing this ticket.
