### ISSUE TITLE
Task: MIRI - LRS Fixed Slit

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/jwst#268] opened 2016-09-20 22:38 UTC
Things to do
- [ ]  Implement algorithm for spatial coordinates

**Comment by brechmos-stsci** [comment] 2016-09-21 12:55
**Blocked** 
- We are waiting for an algorithm for spatial coordinates (waiting on INS)

**Comment by hbushouse** [comment] 2016-09-21 15:55
From David Law on 9/20/2016:

Hi Nadia-

Thanks for the reminder!  I followed up with Alistair, who confirmed that the MIRI imager distortion solution CDP is appropriate to use for both LRS and the coronographs as well (i.e., the CDP polynomials are valid for all pixels on the imaging detector).  Given that, I think what makes the most sense is to have all MIRI modes work on the same basic principle that the ASDF extension gives the mapping to V2,V3 and (if applicable) lambda, with the transform to sky from v2,v3 given by the 5 header keywords (V2_REF, etc).

There will need to be some obvious modifications to account for subarray readout locations and to use the pixel locations of the LRS slit centroid; I can dig into this in greater detail here if you need.  A more tricky question is what to do with the WCS for the LRS slitless subarray; since this is slitless spectroscopy position and wavelength coordinates are degenerate and linked.  This will require more thought; what does HST do for the WCS for grism observations?

For backwards compatibility, it would be good to populate the standard CRPIX, CDELT, etc keywords as well in the cases that they make sense (i.e., imaging mode), with the understanding that they are provided as an approximate convenience and that the ‘gold-standard’ coordinate information is in ASDF+V2_REF/etc keywords.  I think this is compatible with the overall approach being taken for JWST across all instruments?  In the case of the imager, I’d say that this would be done by applying the ASDF+V2_REF/etc keywords, fitting a new overall distortion solution to the result to the accuracy allowed by the CRPIX framework, and saving that information.  CRVAL1/CRVAL2 would probably be the pixel location of the V2_REF/V3_REF reference point for consistency.  Does this sound reasonable to you?

**Comment by nden** [comment] 2016-09-21 17:15
After talking with Howard, we will implement the following:

- identify the row (cross-dispersion direction) of the zero point
- compute V2, V3 (RA, DEC) for each pixel in this row
- replicate this solution for all rows in the fixed slit and slitless domain

I am removing the `blocked` label but still would like to hear what the INS team thinks should be done.

**Comment by stscirij** [comment] 2016-10-05 15:26
Presumably we are going to run extract_2d on MIRI spectroscopic data after assign_wcs is run.  Do we plan to keep them vertical, i.e. have wavelength increasing in the vertical direction?  or should we rotate them so that they resemble NIRSPEC data in having wavelength increasing from left to right?  That would probably make a lot of the subsequent steps much more straightforward...

**Comment by hbushouse** [comment] 2016-10-05 15:32
No, right now the plan is to NOT run extract_2d on MIRI LRS slit or slitless data. It's always a single source and hence there's no need to extract any individual cutouts. The slitless data are already pretty well confined to their own little subarray, which is like a cutout. So the spectra will remain vertical with wavelength running vertically. Extract_1d knows to do its work in the vertical direction for LRS data (there's a dispaxis parameter that tells it the direction).

**Comment by nden** [comment] 2019-04-05 19:09
Resolved by #3106 and other before that.

**Closed by nden** 2019-04-05 19:09 UTC
Labels: MIRI, MIRI LRS, assign_wcs, task
