### ISSUE TITLE
Negative RAs sometimes returned from assign_wcs

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5148] opened 2020-07-16 19:15 UTC
_Issue [JP-1585](https://jira.stsci.edu/browse/JP-1585) was created on JIRA by [Stephanie La Massa](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slamassa):_

I've been testing transformations using routines in the assign_wcs module for a handful of NIRISS imaging (and AMI) simulations. My simulated fields are all at the same Dec and range in RA from 5 - 350 degrees (not in regular intervals).

I found that when inputting detector coordinates into the wcs routine or get_transform('detector', 'world') routine, the returned RA is sometimes correct but sometimes the returned RA is negative (but the RA would be correct if that value was added to 360). For my simulations, RAs <= 155 had the correct RA returned, and RAs >= 230 had negative RAs returned. (Please note: I have not systematically tested this effect over a fine grid of RA values, so I can't say where this turnover from positive to negative RAs happens).

**Comment by stscijgbot-jp** [comment] 2020-07-22 12:20
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=475409#comment-475409):_

[Stephanie La Massa](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slamassa) Could you make the files available so we can test the fix. Thanks!

**Comment by stscijgbot-jp** [comment] 2020-07-23 18:35
_Comment by [Stephanie La Massa](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slamassa) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=475769#comment-475769):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva): The simulated datasets (*_uncal.fits) that I ran through the Detector 1 stage of the pipeline should be accessible here (if I set the permissions on the Box folder correctly!):

<https://stsci.box.com/s/8exjk1ydxok67jjziktajs42xsqkboe8>

Please let me know if you have any trouble accessing the folder!

**Comment by stscijgbot-jp** [comment] 2020-07-24 15:40
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=476011#comment-476011):_

Fixed by #5185

**Comment by mcara** [comment] 2020-07-24 22:08
@nden reported that after #5185 regression tests are failing.

I believe I know the reason: The `detector` to `V2V3` in JWST images are polynomial transformations which are not aware of the wrapping angle. So, when an angle used to be -0.05 deg and now it is 359.95 deg and maybe there is a subtraction of the reference angle `V2ref=0.051` from computed `V2`, in the past one would get `0.001 deg` or 3.6 arcsec but now one gets `395.9 deg` converted to `1425240 arcsec` which then the (inverse) polynomial transformation tries to convert to image coordinates which then results in image coordinates of magnitudes of 1e20 => memory issues attempting to fill polygons in sky background computations.

I can see a couple of approaches to deal with this:

1. revert #5185 and simple adopt the fact that in JWST images RA is defined with a non-standard wrapping angle ([-180, 180] range) and close this issue without any solution.

2. implement a custom inverse to `V23ToSky` so that the inverse (sky-to-v23) returns v2v3 angles in the wrapping understood by polynomials. This will likely require a different model SkyToV23 whose output is wrapped at 180 degrees and these classes will have each other as inverse (this used to cause an recursive issue in `asdf` - but now it is solved);

3. re-design detector->v2v3 polynomial transformations so that v2 angle wraps at 360 and not at 180 degrees;

4. add a another layer (transformation) at the end of the detector->v2v3 transformation that takes care of this wrapping angle change.

Polynomial transformations are used in FITS WCS (SIP convention) but they are used to convert plane-to-plane coordinates. Transformations from plane to sphere use trigonometric functions that are "aware" (know how to handle/are insensitive to) different wrapping angles. Current detector-toV2V3 polynomials in JWST WCS cannot deal with different wrapping angles.

**Comment by hbushouse** [comment] 2020-07-24 22:11
I will at least temporarily revert #5185 until a more permanent solution can be found.

**Comment by mcara** [comment] 2020-07-24 22:22
Which one of the above 4-5 (including 2a & 2b) approaches is more preferable?

**Comment by jdavies-st** [comment] 2020-07-27 15:04
Changing the polynomial coeffs above to work with V2 wrap of 360 deg as you suggest in (3) above will require a new delivery of the `distortion` reference files I suspect.  Is NIRISS imaging the only place we are seeing this problem?  What assumptions are NIRISS making that none of the other teams are about V2/V3?

Is the range of V2 defined well in the JWST SIAF Use and Description white paper?

Internally in the JWST SIAF, there are negative values used throughout the V frame, specifically in V2Ref and V3Ref.

**Comment by stscijgbot-jp** [comment] 2020-07-27 15:35
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=476254#comment-476254):_

[Colin Cox](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cox), any guidance on the standard for the wrap angle of V2 and V3 used for the SIAF polynomial transformations?  I.e. once I go from Idl to V2/V3, what range of angles are V2/V3 supposed to be wrapped to?

This is the python code in `pysiaf` that implements IDEAL > TELESCOPE frame transformation from the JWST SIAF Use and Description white paper.

<https://github.com/spacetelescope/pysiaf/blob/d57e52fa8ce0adfeaa94920f5c31c26e017ef5ed/pysiaf/aperture.py#L909-L1002>

**Comment by stscijgbot-jp** [comment] 2020-07-27 16:05
_Comment by [Colin Cox](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cox) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=476265#comment-476265):_

Since the V2V3 angles are usually small,  much smaller than 90 degrees, I normally allow them to be positive or negative. Essentially I use the natural results of the arcsin and arctan functions. RA is normally assumed to be between 0 and 360 so in that case I add 360 to any negative values. But I think Johannes Sahlmann changed that making it an option with the default being to not make RA positive.

**Comment by stscijgbot-jp** [comment] 2020-07-30 15:20
_Comment by [Colin Cox](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cox) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=477148#comment-477148):_

I might not have understood the full problem here but none of the distortion polynomials will be valid for V2V3 values with absolute values larger than a few hundred arc-sec. They only refer to positions within the JWST field of view. You could place an absolute maximum allowed value of 1000 arc-sec or so. You might be mapping from an instrument aperture to an FGS aperture but even here V2V3's will not be larger than about 800 arc-sec.

**Closed** 2020-08-27 20:08 UTC
Labels: team_periwinkle

**Comment by stscijgbot-jp** [comment] 2020-09-08 19:05
_Comment by [Stephanie La Massa](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slamassa) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=483187#comment-483187):_

I've tested the bug fix by running the same set of simulations through the updated version of the pipeline through Stage 1, and then invoked the assign_wcs module to run the same tests as before. I'm happy to report that the bug is fixed, and no weird behaviors were noticed with the simulations I tested.

**Comment by stscijgbot-jp** [comment] 2020-12-17 22:10
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501026#comment-501026):_

While this is listed as fixed, I ran into the same issue testing pipeline 7.6 yesterday.  Is the fix in pipeline version 0.17.1?  The version is dated 15 September so it should have the fix, but it looks like it is not there.

**Comment by stscijgbot-jp** [comment] 2020-12-17 22:20
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501030#comment-501030):_

[Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk)Can you point us to the data

**Comment by stscijgbot-jp** [comment] 2020-12-17 22:30
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501035#comment-501035):_

The data is at /ifs/jwst/wit/niriss/kevin/pipeline_test3.  I was looking at file jw00042001001_01101_00001_nis_i2d.fits when I saw the negative RA values.  The code was

 

awcs = AssignWcsStep()
 image1 = imagemodel.ImageModel(path+file1)
 gwcs = awcs(image1)

detector_to_world = gwcs.meta.wcs.get_transform('detector', 'world')
 skypos = self.wcs[index].meta.wcs(x1, y1)

 

where the image name is stored in variable file1, path is the path to the image ('./' here), (x1, y1) is the pixel position reported for a source in the field.

If you cannot "see" /ifs/jwst/wit/niriss I can copy the files elsewhere.

**Comment by mcara** [comment] 2020-12-18 00:15
$ ls /ifs/jwst/wit/niriss/kevin/pipeline_test3/
ls: /ifs/jwst/wit/niriss/kevin/pipeline_test3/: Permission denied

**Comment by stscijgbot-jp** [comment] 2020-12-18 01:15
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501041#comment-501041):_

In addition to placing the test file to an accessible location, could you, please run:
```java
import jwst, astropy, gwcs, tweakwcs
print(f'{jwst.__version__}\n{astropy.__version__}\n{gwcs.__version__}\n{tweakwcs.__version__}')```
and report here printed version numbers? Thanks!

**Comment by stscijgbot-jp** [comment] 2020-12-18 01:15
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501042#comment-501042):_

And also the numeric values of x1 and y1.

**Comment by stscijgbot-jp** [comment] 2020-12-18 02:40
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501044#comment-501044):_

I am in the process of copying the files to /user/volk/pipeline_test3/ so I hope you can "see" those files.

 

Running the commands above gives

witserv5 pipeline_test3 > python
 Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
 [GCC 7.3.0] :: Anaconda, Inc. on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> import jwst, astropy, gwcs, tweakwcs
 >>> print(f'{jwst.*_version_*}\n{astropy.*_version_*}\n{gwcs.*_version_*}\n{tweakwcs.*_version_*}')
 0.16.2
 4.0
 0.13.0
 0.6.4

 

As for the pixel positions where the negative RAs were found, it looks like anywhere on the array will do.  If I ask the code to print out (x1, y1) and the sky position for the cursor on the image when the value of RA is negative I get things like the following:

990 1063 [array(-170.79830146), array(46.82626318)]
 986 1067 [array(-170.79819436), array(46.8263361)]
 986 1076 [array(-170.79819233), array(46.82650081)]
 977 1081 [array(-170.79795227), array(46.82659166)]
 968 1094 [array(-170.79771041), array(46.82682892)]
 955 1107 [array(-170.79736235), array(46.82706588)]
 941 1130 [array(-170.79698549), array(46.82748576)]
 928 1148 [array(-170.79663631), array(46.8278142)]
 888 1192 [array(-170.79556448), array(46.82861637)]
 874 1210 [array(-170.79518875), array(46.82894469)]
 834 1268 [array(-170.79411376), array(46.83000291)]
 812 1304 [array(-170.79352159), array(46.83065989)]
 789 1349 [array(-170.79290083), array(46.83148143)]
 763 1402 [array(-170.7921986), array(46.83244904)]
 736 1465 [array(-170.79146756), array(46.83359943)]
 700 1541 [array(-170.79049462), array(46.83498679)]
 651 1626 [array(-170.78917452), array(46.83653749)]
 597 1715 [array(-170.7877207), array(46.83816069)]
 535 1800 [array(-170.78605535), array(46.83970975)]
 459 1876 [array(-170.78402028), array(46.84109262)]
 383 1956 [array(-170.78198411), array(46.84254839)]
 267 2059 [array(-170.7788803), array(46.8444205)]

**Comment by stscijgbot-jp** [comment] 2020-12-18 03:50
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501045#comment-501045):_

The fix is in `jwst>=0.17.0`, i.e. Build 7.6 as indicated above in this issue.  Kevin, update to the latest version of the pipeline:

`pip install -U jwst`

and test again.  It should be fixed.

**Comment by stscijgbot-jp** [comment] 2020-12-18 05:45
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501046#comment-501046):_

Yeah, I was digging through changelog and tags and releases and I agree that the issue is in the version as James pointed out.

**Comment by stscijgbot-jp** [comment] 2020-12-18 15:50
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-1585?focusedCommentId=501103#comment-501103):_

I thought I installed version 0.17.1 as per the instructions using `"pip install jwst==0.17.1`".  I am not sure what has gone wrong here.  My apologies for the mistake.
