### ISSUE TITLE
x1d file with more than one  EXTRACT1D BinTableHDU

### ISSUE THREAD

**Issue by Aseman7** [spacetelescope/jwst#7428] opened 2023-01-10 16:18 UTC
Hello, I encounter three EXTRACT1D BinTableHDU instead of one EXTRACT1D table for some x1d.fits files. Would you please see the following information for this one; how can I solve it?

Filename: jw02589003001_04101_00001-seg003_nis_x1d.fits

No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     357   ()      
  1  SCI           1 ImageHDU        32   ()      
  2  INT_TIMES     1 BinTableHDU     24   1R x 7C   [J, D, D, D, D, D, D]   
  3  EXTRACT1D     1 BinTableHDU     65   2048R x 18C   [D, D, D, D, D, D, D, D, D, D, D, J, D, D, D, D, D, D]   
  4  EXTRACT1D     2 BinTableHDU     65   2048R x 18C   [D, D, D, D, D, D, D, D, D, D, D, J, D, D, D, D, D, D]   
  5  EXTRACT1D     3 BinTableHDU     65   2048R x 18C   [D, D, D, D, D, D, D, D, D, D, D, J, D, D, D, D, D, D]   
  6  ASDF          1 BinTableHDU     11   1R x 1C   [13268B]

**Comment by stscieisenhamer** [comment] 2023-01-11 13:36
Greetings!

The, admittedly short, explanation of the x1d format can be [found in the documentation](https://jwst-pipeline.readthedocs.io/en/latest/jwst/data_products/science_products.html#extracted-1-d-spectroscopic-data-x1d-and-x1dints).

For your specific case, NIRISS SOSS which is a Time Series Observation, each EXTRACT1D HDU is the spectra at each integration.

**Comment by Aseman7** [comment] 2023-01-11 14:25
Thank you so much for your reply, so as for my specific case I am facing with a **x1dints** file not a **x1d**, right? now my question is:

how can I produce a real "x1d" file? According to the JWST pipeline documentation, I can use clabb_spec2  for this aim.

So I run this line:

> $strun calwebb_spec2 jw00017001001_01101_00001_nrca1_rate.fits

but, I did not get "x1d" file (while when I ran it on rateints file, I received  x1dint file ). I don't know about "x1d" where is the problem.

Also, I tried by extract_1d class as:

> $strun extract_1d jw00017001001_01101_00001_nrca1_cal.fits

and I got extract1dstep.fits file not x1d file.

**Comment by stscieisenhamer** [comment] 2023-01-11 15:11
As stated in the related #7429 issue, for time series data, the only supported results is the time series based results, or the 'ints' files.

It is up to the researcher on what further processing is to be done, based on the goals of the research. If you wish to average the individual integrations, there is no specific JWST calibration code that does that. However, there plenty of options using various other Python libraries, such as numpy.

As noted, each EXTRACT1D HDU contains the spectrum at each integration. Using `jwst.datamodels`, as intended, these integrations are in the `spec` attributed of the model. The Python example would be:

>>> import jwst.datamodels as dm
>>> model = dm.open('desired_x1dints.fits')
>>> model.spec[0]  #  The first integration

And from there do whatever further processing on the `model.spec[N]` spectra is desired.

Further information about the models, and in this case the MultiSpecModel, can be [found in the documentation](https://jwst-pipeline.readthedocs.io/en/latest/api/jwst.datamodels.MultiSpecModel.html#jwst.datamodels.MultiSpecModel).

If you have further, science-oriented questions, a better forum to start with is the [JWST Help Desk](https://jwst-docs.stsci.edu/jwst-help-desk). When in doubt, feel free to file further issues here!

**Comment by Aseman7** [comment] 2023-01-13 11:54
Many thanks for the clarification. 

Using the idea that you mentioned, I played with hdu tables in "x1dints" file as  follow by another way (because model.spec[0] didn't work) and fortunately the problem was solved. Then I plotted the spectrum too easily.  Now just I want to be sure that each hdu[N] (please see the following code) is correct as an extracted 1D spectrum and I can use it as input for my analysis? For example this x1dint file has three EXTRACT1D HDU tables. So I have three spectrum that can I use them? All of them are correct for analysing?

> 
> with fits.open('jw02589003001_04101_00001-seg003_nis_x1dints.fits') as hdu:
>     asn_table = Table(hdu[3].data)
> print(asn_table)

 WAVELENGTH              FLUX          ... BKGD_VAR_FLAT NPIXELS
------------------ ---------------------- ... ------------- -------
 2.836636339034307                    nan ...           0.0     0.0
 2.835625321171014                    nan ...           0.0     0.0
2.8346143033077214                    nan ...           0.0     0.0
 2.833603285444429                    nan ...           0.0     0.0
2.8325922922740636                    nan ...           0.0     0.0
 2.831581377336708 2.8436148369117435e-06 ...           0.0    40.0
 2.830570564066973 1.0111411427155405e-06 ...           0.0    40.0
               ...                    ... ...           ...     ...
0.8544734743361369  5.455747106523586e-09 ...           0.0    40.0
0.8535890521097131  8.349608944531716e-09 ...           0.0    40.0
0.8527048623974017                    nan ...           0.0     0.0
0.8518209054329983                    nan ...           0.0     0.0
0.8509371835440672                    nan ...           0.0     0.0
0.8500537233369803                    nan ...           0.0     0.0
0.8491705293777567                    nan ...           0.0     0.0
Length = 2048 rows

**Comment by hbushouse** [comment] 2023-02-22 14:26
NIRISS SOSS x1dints files have multiple EXTRACT1D extensions to store not only the extracted spectra from each individual integration, but also different spectral orders. Typically there will be 3 spectral orders extracted, so in the regular x1dints file that comes out of either calwebb_spec2 or calwebb_tso3 you'll have extensions for:

int_num=n, sporder=1
int_num=n, sporder=2
int_num=n, sporder=3
int_num=n+1, sporder=1
int_num=n+1, sporder=2
int_num=n+1. sporder=3
int_num=n+2, sporder=1
etc.

So if you want to average together the extracted spectra from different integrations (which is what you'd get from an x1d file, as opposed to x1dints), be careful to select based on spectral order and integration number. You can then get an average for each of the 3 orders individually.

The x1dints file that you mentioned above, which only has 3 EXTRACT1D table extensions in it to begin with, sounds like it might contain data for only 1 integration and the 3 tables are for the 3 different spectral orders. You can check the values of the INT_NUM and SPORDER keywords in the header of each EXTRACT1D extension (e.g. hdu[3].header['int_num'] and hdu[3].header['sporder']).

**Comment by hbushouse** [comment] 2023-03-15 19:18
The original file that started this query was "jw02589003001_04101_00001-seg003_nis_x1d.fits", which is obviously a regular "x1d" file, as opposed to an "x1dints" file. An "x1d" file will have only 1 set of extracted data for the whole exposure, as opposed to one extraction per integration. So that suggests that the 3 table extensions in that file are simply for different spectral orders, e.g. orders 1, 2, and 3. That can be confirmed by looking for the value of the "SPORDER" keyword in the header of each table extension.

On the other hand, if this observation really was from NIRISS SOSS taken in TSO mode, then it also should've been processed as a TSO, in which case an "x1d" file should not even be created. The calwebb_spec2 pipeline should've been fed a "rateints" file as input, which has a stack of data for each integration, and it should've produced an "x1dints" file as output, containing extracted spectra for each individual integration. Or was this file produced by manually running the calwebb_spec2 pipeline using the "rate" file as input, and thus resulting in an "x1d" output?

**Comment by nden** [comment] 2023-04-01 20:29
@Aseman7  Can we close this issue or is a follow up needed?

**Comment by nden** [comment] 2023-06-11 13:29
Closing this, please open another issue if there are additional questions

**Closed by nden** 2023-06-11 13:29 UTC
Labels: question, extract_1d, NIRISS SOSS
