### ISSUE TITLE
Assertion error from spherical_geometry

### ISSUE THREAD

**Issue by Guang91** [spacetelescope/jwst#4822] opened 2020-04-18 02:33 UTC
Hi, 

I'm running the pipeline on simulated MIRI images. 
But I got a weird "assertion error" below. 
Could you help me fix it, please?  

Thanks,
Guang

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-568267f985aa> in <module>
     21     img3 = Image3Pipeline()
---> 22     res_step1 = img3.tweakreg.run(asn)
     23     res_step2 = img3.skymatch.run(res_step1)
     24     res_step3 = img3.outlier_detection.run(res_step2)

~/software/jwst/jwst/stpipe/step.py in run(self, *args)
    390                     self.prefetch(*args)
    391                 try:
--> 392                     step_result = self.process(*args)
    393                 except TypeError as e:
    394                     if "process() takes exactly" in str(e):

~/software/jwst/jwst/tweakreg/tweakreg_step.py in process(self, input)
    172 
    173         try:
--> 174             align_wcs(
    175                 imcats,
    176                 refcat=None,

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/tweakwcs/imalign.py in align_wcs(wcscat, refcat, enforce_user_order, expand_refcat, minobj, match, fitgeom, nclip, sigma)
    562 
    563         else:
--> 564             gcat = WCSGroupCatalog(
    565                 wcatalogs,
    566                 name='GROUP ID: {}'.format(group_id)

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/tweakwcs/wcsimage.py in __init__(self, images, name)
    518 
    519         self._name = name
--> 520         self.update_bounding_polygon()
    521         self._catalog = self.create_group_catalog()
    522 

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/tweakwcs/wcsimage.py in update_bounding_polygon(self)
    584         polygons = [im.polygon for im in self._images]
    585         if polygons:
--> 586             self._polygon = SphericalPolygon.multi_union(polygons)
    587         else:
    588             self._polygon = SphericalPolygon([])

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/spherical_geometry/polygon.py in multi_union(cls, polygons)
   1163 
   1164         g = graph.Graph(all_polygons)
-> 1165         return g.union()
   1166 
   1167     def intersection(self, other):

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/spherical_geometry/graph.py in union(self)
    405         """
    406         self._find_all_intersections()
--> 407         self._sanity_check("union - find all intersections")
    408         self._remove_interior_edges()
    409         self._sanity_check("union - remove interior edges")

~/anaconda3/envs/jwst_env/lib/python3.8/site-packages/spherical_geometry/graph.py in _sanity_check(self, title, node_is_2)
    388                 assert len(node._edges) % 2 == 0
    389             else:
--> 390                 assert len(node._edges) >= 2
    391             for edge in node._edges:
    392                 assert node in edge._nodes

AssertionError:

**Comment by Guang91** [comment] 2020-04-18 03:09
I just realized that's caused by different python versions. 
This error occurs in python 3.8, but it disappears in python 3.7 environment.

**Comment by jdavies-st** [comment] 2020-04-20 14:38
What version of the pipeline are you running?  Latest `master` or our latest tagged release?

```
>>> import jwst
>>> print(jwst.__version__)
```

**Comment by Guang91** [comment] 2020-04-20 14:59
>>> jwst.__version__
'0.15.2.dev63+gc0c8ae3d'
>>> tweakwcs.__version__
'0.6.3'

**Comment by jdavies-st** [comment] 2020-04-20 15:51
@mcara any ideas?  Looks like a problem in `spherical_geometry`.

Any chance you can share the dataset(s) that produced this error so that we can reproduce?

**Comment by Guang91** [comment] 2020-04-20 16:05
The datasets are available at https://www.dropbox.com/sh/uaad9ccdipl4p6e/AACRlqnZMP_RNLy5zid4w_x_a?dl=0


The code is below
from jwst.pipeline import Image3Pipeline
from jwst.associations import asn_from_list
from glob import glob
stage2_files = sorted( glob('*stage2.fits') )
asn = dict( asn_from_list.asn_from_list(stage2_files, rule=Asn_Image, product_name='l3_results') )
asn["asn_type"] = "image3"
asn["asn_id"] = ""
img3 = Image3Pipeline()
res_step1 = img3.tweakreg.run(asn)
res_step2 = img3.skymatch.run(res_step1)
res_step3 = img3.outlier_detection.run(res_step2)

**Comment by mcara** [comment] 2020-04-20 16:13
Yes, it is in spherical geometry. I did not look at the file, but I suspect that the input files either have identical or almost identical footprints on the sky.

**Comment by mcara** [comment] 2020-04-20 16:14
What is the version of `spherical_geometry`?

**Comment by Guang91** [comment] 2020-04-20 17:28
> Yes, it is in spherical geometry. I did not look at the file, but I suspect that the input files either have identical or almost identical footprints on the sky.

Correct. These have almost identical footprints. 

> What is the version of `spherical_geometry`?

>>> spherical_geometry.__version__
'1.2.18'

**Comment by jdavies-st** [comment] 2020-04-20 20:44
Given that these are `AssertionErrors` in `spherical_geometry` and that asserts get stripped out  in `python -O`, it's probably not the best way to make checks in the code.  If its an important check, failure should return a useful error (and useful message) that can be caught and handled by the calling routine.

Worth filing an issue in `spherical_geometry`?

**Comment by jdavies-st** [comment] 2020-04-21 20:16
I think this PR

https://github.com/spacetelescope/spherical_geometry/pull/132

was intended to help with this issue, but it was never merged (and never completed?)  Just a thought.

**Comment by mcara** [comment] 2021-05-14 01:49
The issue should be fixed/ameliorated by https://github.com/spacetelescope/tweakwcs/pull/138

**Closed** 2021-05-20 22:29 UTC
Labels: tweakreg
