### ISSUE TITLE
write tests for the master background subtraction step

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3085] opened 2019-02-05 18:49 UTC
40 sp

Write tests for the manual mode of the master background subtraction step.

- [x] `expand_to_2d` function unit test - #3188
- [x] regression tests for supported modes - #3109

**Comment by jemorrison** [comment] 2019-02-08 18:04
An outline of the regression test.
To test the step certain types of data was created. 
a.  The input science that is was created for the step is:  the 2-D background image was added to the 2-D science image.   If this is NIRSPEC FS then also  run extract 2-D on this data to produced FS data. MULTISLIT. For the  IFUs and MIRI LRS this  data will be 2-D image model.
b.  1-d background extracted spectra of the background data. .

Output of step Background subtracted images (FS or 2-D images)

Test 1. Compare the background subtracted image from the step to the science image without the background added. These images will not be exactly the same because the 1-D background spectra used in the step is  inflated to a 2-D image and this  subtracted 2-D image will not exactly match the 2-D background image  (that was added to the science data to create the input to the step) .  The test  perform statisticss on the  smoothed difference image  of the  science image and the output from the master background step to confirm it meets certain requirements. 

Test 2. Compare the 1-D extracted spectra from the clean science image (with no background added) and the 1-D extracted spectra from the output of the master background step. These 1-D images should be very close (almost exact). 

Test 3. After confirming the step is working (Test 1 and Test 2 pass) then set up the truth file of the master background subtraction step.

**Comment by hbushouse** [comment] 2019-03-14 12:53
Fixed by #3109

**Closed by hbushouse** 2019-03-14 12:53 UTC
Labels: master background, task
