### ISSUE TITLE
TST: Fix regression tests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2508] opened 2018-09-14 14:36 UTC
I was snoping around and behold: https://boyle.stsci.edu:8081/job/RT/job/JWST/280/console

`======= 23 failed, 97 passed, 5 xfailed, 286 warnings in 9357.82 seconds =======`

**Comment by jdavies-st** [comment] 2018-09-14 15:05
Yup!  A better view:

https://boyle.stsci.edu:8081/job/RT/job/JWST/test_results_analyzer/

Dave needs to update the tests as he committed new code for ramp fitting.  We are on top of this.  =)


On Sep 14, 2018, at 10:36 AM, P. L. Lim <notifications@github.com<mailto:notifications@github.com>> wrote:


I was snoping around and behold: https://boyle.stsci.edu:8081/job/RT/job/JWST/280/console

======= 23 failed, 97 passed, 5 xfailed, 286 warnings in 9357.82 seconds =======

**Comment by hbushouse** [comment] 2018-10-04 15:42
Given that there are at least 2 of us actively monitoring and fixing regression tests on a daily basis, without any prompting from tickets, issues, or hecklers, I think we can close this. If not, we basically have to leave it open forever, because we will always be updating regression tests.

**Closed by hbushouse** 2018-10-04 15:42 UTC
