### ISSUE TITLE
GWCS objects from assign_wcs should produce positive RA

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1919] opened 2018-04-19 19:57 UTC
The GWCS objects that map pixels to sky can sometimes produce negative RA values, even if the input RA_REF header keyword is positive.  One needs to add 360 to get them positive sometimes.

This feature is handled properly when we compute footprints, so that we get positive footprints on the sky, but one could imagine if one is taking the difference of two sky coordinates to compute a size, this could cause a problem if two adjacent sky coords have RA values off by ~360 degrees.

We should make sure that we always produce positive RA values, as that way we don't have to keep track if we're ever taking differences of two sky coordinates to compute sizes or footprints in subsequent data analysis tools.

This could be handled in the `V23ToSky` transform or the `pointing.v23tosky` calling function - a single location for all JWST instruments.

Thoughts?

**Comment by nden** [comment] 2020-08-10 18:01
Duplicate of #5206

**Comment by nden** [comment] 2020-10-10 21:04
Fixed by #5206

**Closed by nden** 2020-10-10 21:04 UTC
Labels: assign_wcs
