### ISSUE TITLE
Ramp fit with multiprocessing hangs on macOS

### ISSUE THREAD

**Issue by chriswillott** [spacetelescope/jwst#6266] opened 2021-08-09 20:21 UTC
I am running jwst pipeline version 1.3.0 on a Mac with os version Catalina 10.15.7.

When I run ramp fitting without multiprocessing it runs fine. But when I set ramp_fit.maximum_cores = 'half' the pipeline does not run to completion. It looks like there is a loop that creates multiple processes of the main routine so that all the pipeline steps get run multiple times and the machine memory gets consumed rapidly. I have googled and found some issues around how multiprocessing processes are started (using either spawn or fork) in more recent versions of macOS.

I do not see this problem when running the same code on a linux machine.

Here is part of the stacktrace:

```
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/refpix/reference_pixels.py", line 1847, in reference_pixel_correction
    input_dataset.do_corrections()
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/refpix/reference_pixels.py", line 873, in do_corrections
    self.do_fullframe_corrections()
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/refpix/reference_pixels.py", line 889, in do_fullframe_corrections
    self.DMS_to_detector(integration, group)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/refpix/reference_pixels.py", line 1215, in DMS_to_detector
    self.get_group(integration, group)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/refpix/reference_pixels.py", line 287, in get_group
    self.group[:, :] = self.input_model.data[integration, group].copy()
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/willottc/niriss/pipeline/runDetector1_niriss_testnocoljump.py", line 116, in <module>
    result = pipe(rawdirfile)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 134, in process
    result, ints_model = self.ramp_fit(result)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit_step.py", line 70, in process
    out_model, int_model, opt_model, gls_opt_model = ramp_fit.ramp_fit(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py", line 100, in ramp_fit
    new_model, int_model, opt_model = ols_fit.ols_ramp_fit_multi(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/ramp_fitting/ols_fit.py", line 183, in ols_ramp_fit_multi
    real_results = pool.starmap(ols_ramp_fit_sliced, slices)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/willottc/niriss/pipeline/runDetector1_niriss_testnocoljump.py", line 116, in <module>
    result = pipe(rawdirfile)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 115, in process
    result = self.dark_current(result)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/dark_current/dark_current_step.py", line 50, in process
    dark_model = datamodels.DarkModel(self.dark_name)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/datamodels/dark.py", line 30, in __init__
    super(DarkModel, self).__init__(init=init, **kwargs)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/datamodels/reference.py", line 21, in __init__
    super(ReferenceFileModel, self).__init__(init=init, **kwargs)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 233, in __init__
    asdffile = fits_support.from_fits(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 611, in from_fits
    known_keywords, known_datas = _load_from_schema(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 531, in _load_from_schema
    mschema.walk_schema(schema, callback)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 149, in walk_schema
    recurse(schema, [], None, ctx)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 137, in recurse
    recurse(val, path + [key], combiner, ctx)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 124, in recurse
    if callback(schema, path, combiner, ctx, recurse):
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 509, in callback
    result = _fits_array_loader(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 461, in _fits_array_loader
    return from_fits_hdu(hdu, schema)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 640, in from_fits_hdu
    data = hdu.data
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/utils/decorators.py", line 767, in __get__
    val = self.fget(obj)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 240, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 779, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 529, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/file.py", line 329, in readarray
    data = _array_from_file(self._file, dtype, count)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/util.py", line 580, in _array_from_file
    return np.fromfile(infile, dtype=dtype, count=count)
KeyboardInterrupt

/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Chris Willott

**Comment by kmacdonald-stsci** [comment] 2021-08-10 15:19
Hi Chris,

The multiprocessing has been refactored and has now been moved to STCAL.  If you want to use JWST 1.3.0, please let me know what data you are using so I can reproduce this bug and investigate this problem.

-Ken

**Comment by chriswillott** [comment] 2021-08-10 21:01
Hi Ken,

If you have access to the following data at STScI you should be able to find a NIRISS file I was trying to process: /ifs/jwst/wit/niriss/swara/NIS_CARS/NIS-015/simulations/sims_files/jw01089001001_01101_00001_nis_uncal.fits

Chris

**Comment by kmacdonald-stsci** [comment] 2021-08-12 14:10
Chris,

I copied that file locally.  I am running MacOS 10.15.7, python 3.8.11, and jwst 1.3.0 and it runs fine for me.  I run the whole pipeline setting ramp_fit.maximum_cores to “none”, “quarter”, “half”, and “all”.  The entire pipeline ran to completion.  Also, I used a jump file from the pipeline run to run RampFitStep.call on a jump file.  I ran this function with maximum_cores being set as above and, again, it all ran to completion just fine.

I do get that resource tracker warning at the end, but I do not get the back trace that you get.  I'm not sure if you get the back trace because of the keyboard interrupt, but that warning at the end isn't a hang, for me anyway.  If you simply hit return, instead of an interrupt, do you still have problems?

**Comment by jdavies-st** [comment] 2021-08-12 14:58
I'll add here that it looks like there are 3 tracebacks the stack trace above @chriswillott.  It's not clear which is the real problem.

The following

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/willottc/niriss/pipeline/runDetector1_niriss_testnocoljump.py", line 116, in <module>
    result = pipe(rawdirfile)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 115, in process
    result = self.dark_current(result)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/dark_current/dark_current_step.py", line 50, in process
    dark_model = datamodels.DarkModel(self.dark_name)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/datamodels/dark.py", line 30, in __init__
    super(DarkModel, self).__init__(init=init, **kwargs)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/jwst/datamodels/reference.py", line 21, in __init__
    super(ReferenceFileModel, self).__init__(init=init, **kwargs)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 233, in __init__
    asdffile = fits_support.from_fits(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 611, in from_fits
    known_keywords, known_datas = _load_from_schema(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 531, in _load_from_schema
    mschema.walk_schema(schema, callback)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 149, in walk_schema
    recurse(schema, [], None, ctx)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 137, in recurse
    recurse(val, path + [key], combiner, ctx)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/schema.py", line 124, in recurse
    if callback(schema, path, combiner, ctx, recurse):
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 509, in callback
    result = _fits_array_loader(
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 461, in _fits_array_loader
    return from_fits_hdu(hdu, schema)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 640, in from_fits_hdu
    data = hdu.data
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/utils/decorators.py", line 767, in __get__
    val = self.fget(obj)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 240, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 779, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 529, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/file.py", line 329, in readarray
    data = _array_from_file(self._file, dtype, count)
  File "/Users/willottc/opt/anaconda3/envs/jwst1p3p0/lib/python3.9/site-packages/astropy/io/fits/util.py", line 580, in _array_from_file
    return np.fromfile(infile, dtype=dtype, count=count)
KeyboardInterrupt
```

Looks to me like each multiprocessing job is trying to open the dark current reference file, but if it hasn't been downloaded locally (perhaps?) this is what is causing it to feel like a hang?   These dark reffiles are huge, on the order of GB, and CRDS has been very slow lately.  Hopefully you've got local CRDS cache setup correctly.

Also, what is `runDetector1_niriss_testnocoljump.py`?  It looks like from the traceback, that script is being run under multiprocessing.  Is this the case?  It looks like it is running the whole `Detector1Pipeline`, not just jump, and it is hanging when trying to download the dark reffile for `DarkCurrentStep`, which is very early in the pipeline, before it even gets to ramp fitting.  This part of the traceback looks unrelated to anything in ramp fitting.

**Comment by chriswillott** [comment] 2021-08-12 16:16
Thanks for both your feedback. This has helped me to narrow down the issue. I have pared down my script to just the basic running of the pipeline and still get the same issue. However, if I just paste the commands into a python session the pipeline runs fine without hanging. So when I run it as a script the whole script gets restarted multiple times during the ramp_fit stage in a never-ending loop. This is my script:

`#!/usr/bin/env python

from jwst.pipeline import Detector1Pipeline

print ('starting script now')
rawdirfile = '/Users/willottc/niriss/commissioning/rehearsals/may2021/nis015/raw/jw01089001001_01101_00001_nis_uncal.fits'

#Perform first section of level 1 pipeline 
pipe = Detector1Pipeline()
pipe.ipc.skip = True
pipe.persistence.skip = True
pipe.jump.rejection_threshold = 5.0
pipe.jump.maximum_cores = 'none'
pipe.jump.flag_4_neighbors = True
pipe.jump.max_jump_to_flag_neighbors = 2000
pipe.jump.min_jump_to_flag_neighbors = 10
pipe.ramp_fit.maximum_cores = 'half'  
pipe.save_results = True
result = pipe(rawdirfile)
` 

Could you test and see if you get the same behaviour when running as a script? I did a full reinstall of Anaconda before posting the issue to see if this would get fixed and it didn't. Perhaps there is something else in my environment causing this?

Here is a more relevant part of the traceback showing the first run of the ramp fitting step and then the multiple startup of the script:

`2021-08-12 09:11:56,567 - stpipe.Detector1Pipeline.jump - INFO - Step jump done
2021-08-12 09:11:56,628 - stpipe.Detector1Pipeline.ramp_fit - INFO - Step ramp_fit running with args (<RampModel(1, 5, 2048, 2048) from jw01089001001_01101_00001_nis_uncal.fits>,).
2021-08-12 09:11:56,629 - stpipe.Detector1Pipeline.ramp_fit - INFO - Step ramp_fit parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/Users/willottc/niriss/commissioning/rehearsals/may2021/nis015/raw', 'int_name': '', 'save_opt': False, 'opt_name': '', 'maximum_cores': 'half'}
2021-08-12 09:11:56,662 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using READNOISE reference file: /Users/willottc/crds_cache/references/jwst/niriss/jwst_niriss_readnoise_0002.fits
2021-08-12 09:11:56,680 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using GAIN reference file: /Users/willottc/crds_cache/references/jwst/niriss/jwst_niriss_gain_0002.fits
2021-08-12 09:11:56,698 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using algorithm = ols
2021-08-12 09:11:56,698 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using weighting = optimal
starting script now
starting script now
starting script now
2021-08-12 09:11:58,687 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2021-08-12 09:11:58,688 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
starting script now
2021-08-12 09:11:58,689 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
starting script now
2021-08-12 09:11:58,690 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2021-08-12 09:11:58,690 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2021-08-12 09:11:58,691 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2021-08-12 09:11:58,691 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2021-08-12 09:11:58,691 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2021-08-12 09:11:58,692 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2021-08-12 09:11:58,692 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2021-08-12 09:11:58,692 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2021-08-12 09:11:58,693 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2021-08-12 09:11:58,693 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2021-08-12 09:11:58,694 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2021-08-12 09:11:58,694 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2021-08-12 09:11:58,695 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2021-08-12 09:11:58,695 - stpipe.Detector1Pipeline.rscd - INFO - RscdStep instance created.
2021-08-12 09:11:58,696 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
starting script now
2021-08-12 09:11:58,696 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2021-08-12 09:11:58,696 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2021-08-12 09:11:58,697 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2021-08-12 09:11:58,697 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2021-08-12 09:11:58,697 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2021-08-12 09:11:58,698 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
`

**Comment by chriswillott** [comment] 2021-08-12 20:22
There is an error when I run the pipeline in this script. The script never reaches completion. During the ramp fit step, multiprocessing triggers several processes that run the entire script from the start. Each of these then triggers more copies of the script and more processes, etc. until all resources on the machine are consumed. The excerpt from the output log I showed above shows that just after the line `stpipe.Detector1Pipeline.ramp_fit - INFO - Using weighting = optimal` the print statement at the beginning of the script is printed 6 times. 

I don't understand why I am getting this whereas you do not. Here are my versions numbers:
python                    3.9.6
jwst                      1.3.0
but I had the same problem with a previous version of jwst running on python 3.8

As an additional test I just set the ramp fit cores to zero and the jump fit cores to half and I had the same problem. So it doesn't seem to be specific to ramp fit. Therefore perhaps it is not a problem with the jwst package but something more general in my environment that does not work well with multiprocessing.

**Comment by kmacdonald-stsci** [comment] 2021-08-13 00:27
That is strange.  The `stpipe.Detector1Pipeline.ramp_fit - INFO - Using weighting = optimal` comes from the step code at 

https://github.com/spacetelescope/jwst/blob/4235b1dd5ea7f9bf457af68c564bcb8ad6ecd7ce/jwst/ramp_fitting/ramp_fit_step.py#L64

This well before the multiprocessing, which happens at 

https://github.com/spacetelescope/jwst/blob/4235b1dd5ea7f9bf457af68c564bcb8ad6ecd7ce/jwst/ramp_fitting/ols_fit.py#L183

At the moment I have no idea why it appears your code is being multiprocessed before the step code is invoked.  I'll talk with James more about this tomorrow to see if he has any ideas.

Just so you can see the output I am seeing, I copied your above script steps into `det1pipeline_minimum.txt` (the extension is text so it can be uploaded in this comment).  I ran this script and put the output from that run in `2021_08_12_1249_det_min_output.txt`.

[2021_08_12_1249_det_min_output.txt](https://github.com/spacetelescope/jwst/files/6979192/2021_08_12_1249_det_min_output.txt)

[det1pipeline_minimum.txt](https://github.com/spacetelescope/jwst/files/6979193/det1pipeline_minimum.txt)

**Comment by chriswillott** [comment] 2021-08-13 04:50
Hi Ken,

I downloaded your script det1pipeline_minimum.txt and it runs as expected and there is no problem. The difference between your script and mine is that you place the call to the pipeline in a function and protect it with __main__. I believe this is what stops multiprocessing from spawning multiple copies of the full script. I'm no expert on multiprocessing but here are a few things I found by google:
https://twitter.com/raymondh/status/1180209729609420800?lang=en
https://stackoverflow.com/questions/60691363/runtimeerrorfreeze-support-on-mac
In the second link it sounds very similar to my issue (and indeed I saw the 'freeze_support' error message if I left my program to run for a while).

**Comment by kmacdonald-stsci** [comment] 2021-08-13 13:10
Hi Chris,

I modified my above script to remove it as a function to run as a script, rather than as functions, and it went crazy the same as yours.  I, too, got the `freeze_support` error message.  Reading through the links above it does look like that is the problem.  That running multiprocessing as just a script, rather than using main, will fail due to the way multiprocessing itself works.  That's a good subtle detail to know about multiprocessing.

**Comment by kmacdonald-stsci** [comment] 2021-08-13 14:22
Since this is due to a subtlety with using the `multiprocessing` module and resolved by using the `if __name__=="__main__"` convention when calling the pipeline, this issue is now closed.

**Closed by kmacdonald-stsci** 2021-08-13 14:22 UTC
Labels: multiprocessing
