### ISSUE TITLE
Running NRS LAMP exposure through calwebb_spec2

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3093] opened 2019-02-06 19:30 UTC
An exposure with `EXP_TYPE=NRS_IFU` with the following instrument configuration

```
{'detector': 'NRS1',
 'filter': 'OPAQUE',
 'grating': 'G140M',
 'lamp_state': 'LINE1',
 'name': 'NIRSPEC',}
```

fails in cube_build when run through calwebb_spec2. 
Should this go through cube_build at all (see #1782)?
Is there a special pipeline for NRS internal lamp observations?

Also there are two configuration files: `calwebb_nrslamp-spec2.cfg` and the identical `calwebb_spec2-nrslamp.cfg`. Which one should be removed?

**Comment by hbushouse** [comment] 2019-02-06 19:37
`calwebb_spec2-nrslamp.cfg` is the one that should be removed. The naming scheme was changed a while ago, which is when `calwebb_nrslamp-spec2.cfg` was created to fit the new scheme.

**Comment by hbushouse** [comment] 2019-02-06 19:43
#1782 (and the corresponding https://jira.stsci.edu/browse/JP-282) don't seem to address IFU exposures, so I've added that question to https://jira.stsci.edu/browse/JP-282.

**Comment by hbushouse** [comment] 2019-02-07 02:01
Additional information regarding the processing of NIRSpec internal lamp exposures has been given in https://jira.stsci.edu/browse/JP-473, which includes an attachment listing the calspec2 steps to be applied for the different modes (IFU, Slit, MOS) and lamp types. IFU exposures using line lamps are requested to go through the `cube_build` step. Is there sufficient WCS information to do that? What was the cause of the `cube_build` failure when presented with an IFU exposure?

**Comment by hbushouse** [comment] 2019-02-07 02:02
In https://jira.stsci.edu/browse/JP-282 James Muzerolle commented:
```
We need IFU cubes for LINE lamps and autowavecals.  In those cases, the spatial component only corresponds to the MSA plane.  Does cube_build have the ability to resample into that space, or does it require sky coordinates?
```

**Comment by hbushouse** [comment] 2019-07-15 15:13
Related to https://jira.stsci.edu/browse/JP-473 and #2927.

**Comment by nden** [comment] 2021-03-05 20:50
I believe this was resolved already. @hbushouse ?

**Comment by hbushouse** [comment] 2021-03-08 13:11
Yes, B7.7.1 updates now allow NRS lamp exposures in IFU mode to go through cube_build and all of calspec2. Closing.

**Closed by hbushouse** 2021-03-08 13:11 UTC
Labels: NIRSpec IFU, jira, question, spec2 pipeline
