### ISSUE TITLE
Set CRDS context in Jenkins to jwst-edit

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/jwst#2068] opened 2018-05-22 15:22 UTC
CRDS has symbolic names for contexts.   The two primary symbolic names are jwst-operational (runs in pipeline) and jwst-edit (next delivery adds to this by default).  In practice,  jwst-edit tracks the last ReDCaT delivery.

Setting CRDS_SERVER_URL=https://jwst-crds.stsci.edu and CRDS_CONTEXT=jwst-edit should make Jenkins automatically track the last CRDS delivery.   (Unlike the default operational/pipeline context,  jwst-edit currently requires a server connection to translate:  the CRDS client will ask the CRDS server what jwst-edit means.  

Anyway,   Steve's idea,  using jwst-edit,  could eliminate the constant multi-step process of updating the Jenkins and/or Pandokia contexts provided that a CRDS server connection is feasible.   I should be able to remove the "server required" aspect during 7.2 but for now that is one potential drawback.

**Comment by jaytmiller** [comment] 2018-07-24 13:44
We completed this work and it's been working successfully for a couple months.   One loose end is the context used by the nightly regression tests which is still jwst-operational,  the current default.   Should that be updated to the latest delivered context as well?

**Comment by hbushouse** [comment] 2018-07-24 13:48
Where is it that `jwst-operational` is being set for the nightly regression tests? The file `JenkinsRT` is using `jwst-edit` and I thought that was the file controlling the reg tests, but perhaps it's not.

I would agree that we do want the nightly regression tests to use `jwst-edit`.

**Comment by jdavies-st** [comment] 2018-07-24 14:16
The context for nightly regression tests has been set to `jwst-edit` since May 24th.

https://github.com/spacetelescope/jwst/commit/9a88482494a2a96ec6431f222b8b0e91a14477c0#diff-d989dbe11b6a131293f54f52a6458757

It's been working well.  Closing this issue.

**Closed by jdavies-st** 2018-07-24 14:16 UTC
Labels: crds interface, testing
