### ISSUE TITLE
np.bool warning when using numpy 1.20

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwst#5724] opened 2021-02-08 20:24 UTC
When running calwebb_detector1 in a newly created python 3.9 environment with numpy 1.20, there are many iterations of a numpy warning that show up, as seen below. The repeated warnings make the log much longer than it otherwise would be.

```
2021-02-08 15:08:19,238 - stpipe.Detector1Pipeline.ramp_fit - INFO - Step ramp_fit running with args (<RampModel(1, 108, 2048, 2048) from NRCNRCA1-DARK-60011933591_1_481_SE_2016-01-01T20h04m44_level1b_Sept2018_uncal.fits>,).
2021-02-08 15:08:19,239 - stpipe.Detector1Pipeline.ramp_fit - INFO - Step ramp_fit parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/grp/jwst/wit/nircam/reference_files/darks/full_frame/for_commissioning/A1/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/ifs/jwst/wit/nircam/isim_cv3_files_for_calibrations/darks/A1', 'int_name': '', 'save_opt': False, 'opt_name': '', 'maximum_cores': 'none'}
2021-02-08 15:08:19,252 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using READNOISE reference file: /grp/crds/cache/references/jwst/jwst_nircam_readnoise_0025.fits
2021-02-08 15:08:19,274 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using GAIN reference file: /grp/crds/cache/references/jwst/jwst_nircam_gain_0050.fits
2021-02-08 15:08:19,294 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using algorithm = ols
2021-02-08 15:08:19,294 - stpipe.Detector1Pipeline.ramp_fit - INFO - Using weighting = optimal
2021-02-08 15:11:00,445 - stpipe.Detector1Pipeline.ramp_fit - WARNING - /user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py:1999: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  got_case = np.zeros((asize1*asize2), dtype=np.bool)

2021-02-08 15:11:40,547 - stpipe.Detector1Pipeline.ramp_fit - WARNING - /user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py:1999: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  got_case = np.zeros((asize1*asize2), dtype=np.bool)

2021-02-08 15:22:02,192 - stpipe.Detector1Pipeline.ramp_fit - WARNING - /user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py:1999: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  got_case = np.zeros((asize1*asize2), dtype=np.bool)

2021-02-08 15:22:22,243 - stpipe.Detector1Pipeline.ramp_fit - WARNING - /user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py:1999: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  got_case = np.zeros((asize1*asize2), dtype=np.bool)
```

I believe this is referring to the line below in ramp_fit.py. I would submit a PR, but I'm not sure which of the two options mentioned in the warning is preferable:
https://github.com/spacetelescope/jwst/blob/master/jwst/ramp_fitting/ramp_fit.py#L2009

**Comment by nden** [comment] 2021-02-19 13:55
Duplicate of #5725

**Closed** 2021-02-19 20:50 UTC
