### ISSUE TITLE
`test_coron` failures with numpy 2.0

### ISSUE THREAD

**Issue by braingram** [spacetelescope/jwst#8579] opened 2024-06-18 19:42 UTC
Several tests in `test_coron.py` fail with numpy 2.0:
- `test_align_fourierLSQ`
- `test_align_array`
- `test_shift_subtract`

https://github.com/spacetelescope/jwst/actions/runs/9570099916/job/26384136420?pr=8576#step:10:284

**Comment by stscirij** [comment] 2024-09-17 15:41
The link to the test failures isn't working anymore.  When I ran the coron unit tests under numpy 1.26, they passed.  When I ran under numpy 2.1.1, the 3 tests named in the first comment failed:
```
- test_shift_subtract
- test_align_fourierLSQ
- test_align_array
```
but the failures were assertion failures, not fatal errors.

**Comment by braingram** [comment] 2024-09-17 15:49
I'm not sure if https://github.com/spacetelescope/jwst/pull/8717 also addresses the numpy 2.x differences.

**Comment by braingram** [comment] 2024-09-17 20:36
#8717 won't address the numpy 2.0 difference as tested with https://github.com/spacetelescope/jwst/pull/8799 (only unit tests were run, not regression tests).

**Comment by melanieclarke** [comment] 2024-09-20 17:24
The remaining issues with the coron unit tests look precision related to me.  Testing locally with numpy 2, I can fix `test_fourier_imshift`, `test_shift_subtract`, `test_align_fourierLSQ`, and `test_align_array` by casting the inputs to np.float64 before calling the function. 

The `test_align_model` test can't be fixed in the same way because the inputs are cast back to float32 when read into the datamodels.  I think here we can just update the expected values for the test and loosen the tolerance, similar to the regression test fix.

I can send a PR in a minute.

**Closed** 2024-09-20 18:12 UTC
